
# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Uncomment this if you are using SSL/TLS, running in Docker container, etc.
# http:
#   base_url: example.duckdns.org:8123

# Text to speech
roku:
  - host: 192.168.1.32

frontend:
  themes: !include_dir_merge_named themes
tts:
  - platform: google_translate

zwave:
  usb_path: /dev/ttyACM0
  config_path: /config/open-zwave_config

 
binary_sensor:
  - platform: template
    sensors:
      front_door_motion:
        device_class: motion
        friendly_name: 'Front Door Motion'
        value_template: "{{ is_state('sensor.front_exterior_motion', '8') }}"
        
sensor:
  - platform: darksky
    api_key: a538f4525f8f5f48b3e2a72722a9cc98
    forecast:
      - 0
    hourly_forecast:
      - 0
      - 1
      - 12
      - 24
    monitored_conditions:
      - summary
      - icon
      - temperature
      - precip_probability
      - precip_intensity
      - precip_type
      - wind_speed
      - humidity
    latitude: 41.723562
    longitude: -71.143404

  - platform: systemmonitor
    resources:
      - type: disk_use_percent
        arg: /home
      - type: processor_use

  - platform: glances
    name: RPI
    host: localhost
    port: 61208
    resources:
      - 'memory_free'

  - platform: template
    sensors:
        hvac:
          friendly_name: "HVAC"
          value_template: >-
            {% if is_state('binary_sensor.hvac_monitor_status', 'off') %}
              Error
            {% elif is_state('binary_sensor.hvac_heat', 'on') %}
              Heat
            {% elif is_state('binary_sensor.hvac_cool', 'on') %}
              Cool
            {% elif is_state('binary_sensor.hvac_fan', 'on') %}
              Fan
            {% else %}
              Off
            {% endif %}
 
  - platform: template
    sensors:
      front_door_motion_sensor_battery:
        friendly_name: 'Front Door Motion Battery Level'
        unit_of_measurement: '%'
        value_template: "{{ state_attr('zwave.front_exterior_motion', 'battery_level') }}"
        device_class: battery

  - platform: template
    sensors:
      gate:
        friendly_name: "Gate Status"
        value_template: >-
          {% if is_state('binary_sensor.pin_gpio2', 'on') %}
            Gate Closed
          {% else %}
            Gate Open
          {% endif %}
glances:
  - host: localhost

timer:
  reset_outdoor_lights:
    name: "Reset Outdoor Lights"
    duration: "00:05:00"
  
  irrigation_5m:
    name: "5m Irrigation Timer"
    duration: "00:05:00"
  
  irrigation_10m:
    name: "10m Irrigation Timer"
    duration: "00:10:00"

  fishtank_reset:
    name: "Fishtank Lights Reset"
    duration: "00:10:00"

notify:
  - name : HangoutsNotifier
    platform: hangouts
    default_conversations:
      - id: "Ugwjd0A2yR1WWtoWbW94AaABAQ"
 
group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml